name: OmniUtilities
main: me.killerkoda13.okutil.Main
version: 1.0.0
description: OmniKraft Utilities package. Made by Killerkoda13(Alex Jones)
commands:
   okutils:
      description: Base command for OmniUtilities plugin.
      usage: /<command>
   lag:
      description: check ms ping to server
      usage: /<command>