name: OmniUtils
main: me.killerkoda13.okutil.Main
version: 0.0.1
description: OmniKraft Utilities package. Made by Killerkoda13(Alex Jones)
commands:
   omniutils:
      description: Base command for OmniUtilities plugin.
      usage: /<command>

